######### Cadastro  closetvirtual

POST http://127.0.0.1:3333/closetvirtual HTTP/1.1
Content-Type: application/json
Authorization:Bearer MQ.2Lh8mEWqtz_cEWBjf13YG0_ap9X85K2fOcqOuBZOey69sd_-zzwUNcg_eJnM

{
    "name":"closetvirtual1"
}

######### Listar todos os closetvirtual

GET http://127.0.0.1:3333/closetvirtual HTTP/1.1
Content-Type: application/json
Authorization:Bearer MQ.2Lh8mEWqtz_cEWBjf13YG0_ap9X85K2fOcqOuBZOey69sd_-zzwUNcg_eJnM
######### Alterar closetvirtual

PUT  http://127.0.0.1:3333/closetvirtual HTTP/1.1
Content-Type: application/json
Authorization:Bearer MQ.2Lh8mEWqtz_cEWBjf13YG0_ap9X85K2fOcqOuBZOey69sd_-zzwUNcg_eJnM

{
    "name": "closetvirtualII"
}

######### Apagar closetvirtual
DELETE http://127.0.0.1:3333/closetvirtual HTTP/1.1
Content-Type: application/json
Authorization:Bearer MQ.2Lh8mEWqtz_cEWBjf13YG0_ap9X85K2fOcqOuBZOey69sd_-zzwUNcg_eJnM